# Site settings
title: Helena Civic Center Board
email: info@helenaciviccenterboard.org
description: > # this means to ignore newlines until "baseurl:"
  The Civic Center Board has raised and spent over two million dollars in renovation and repairs of the Civic Center building.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.helenaciviccenterboard.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# modify version numbers below when upgrading bootstrap
# only the assets directory is needed from the bootstrap-sass download
bootstrap-sass: bootstrap-sass-3.3.4
sass:
    sass_dir: /bootstrap-sass-3.3.4/assets/stylesheets
    style: :compressed

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
