# Site settings
title: Helena Civic Center Board

# https://github.com/benbalter/jekyll-seo-tag#usage
# define image: on each page
logo: icons/apple-touch-icon-180x180.png
social:
  type: Organization
  name: Helena Civic Center Board
  links:
    - https://www.facebook.com/Helena-Civic-Center-Board-Page-944361142309331

google_analytics_id: UA-63713244-1

# Build settings
markdown: kramdown
timezone: US/Mountain

# modify version numbers below when upgrading bootstrap
# only the assets directory is needed from the bootstrap-sass download
bootstrap-sass: bootstrap-sass-3.3.4
sass:
  sass_dir: /bootstrap-sass-3.3.4/assets/stylesheets
  style: :compressed

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

exclude: [vendor, circle.yml, CNAME, Gemfile, Gemfile.lock, Rakefile, README.md]
